# Starship prompt configuration file
# ~/.config/starship.toml

[directory]
style = "bold fg:#f08000"

[git_branch]
style = "bold fg:#c40f4b"

[git_status]
style = "bold fg:#b50000"
ahead = "â‡§"
behind = "â‡©"
modified = "!"
staged_count.enabled = true
staged_count.style = "fg:#f08000"

[python]
format = "[ğŸ $version](bold fg:#474747) "

[cmd_duration]
min_time = 1000
show_milliseconds = true
format = "âŒ› [$duration](fg:#474747)"

[character]
success_symbol = "[â¯](bold fg:#f08000)"
error_symbol = "[âœ—](bold red)"
use_symbol_for_status = true

[jobs]
style = "fg:#474747"
symbol = "â–"

[battery]
disabled = true

[time]
style = "italic fg:3e4e5e"
